- name: Setup VOF base image
  hosts: all
  remote_user: ubuntu
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
    bucket_name: '{{lookup("env", "BUCKET_NAME")}}'
    service_account_json: '{{lookup("env", "SERVICE_ACCOUNT_JSON")}}'
  roles:
    - setup
    - copy-files
    - setup-metricbeat
    - setup-filebeat
    - setup-fluentd
